### ISSUE TITLE
Delete this misogynistic repo immediately

### ISSUE THREAD

**Issue by The-Feminist-Software-Foundation** [Alcesmire/men-kampf-firefox#3]
How dare you compare the noble cause of feminism with that historical piece of shit that was Hitler?  Do you know that, [in 2015, when both gays and blacks have made great advances, women's rights are still stuck stagnant ever since 1983?](http://www.huffingtonpost.com/2015/03/11/madonna-gay-rights-out-magazine_n_6847108.html?utm_hp_ref=gay-voices&ir=Gay+Voices)

In a world where women's rights are less advanced than gay rights, how can you make such a misogynistic and frankly uneducated "satirical Firefox add-on" that reduces the daily struggles of feminists into nothing but a Nazi joke?

Do you have a small penis or are you secretly gay or what?  Why are you so afraid of women?

**Comment by Alcesmire** [comment]
Dear Aryan-Software-Foundation,
I'm deeply sorry if you have been triggered by all this. You're completely right, all jokes and satire are completely out of line if it has any potential for any micro aggressions for anyone.

As a Jew and a part of zionism I apologize to all Germans out there, regardless whether you are master race, übermensch, degenerate or undermensch. I hope nazism can forgive my perpetuation of communism against Germans.

The ever so secretly gay and under-endowed,
Erim Secla

**Comment by rotweiller92** [comment]
Code is working well and there's no reported bug in this issue. At this point there's no reason to keep it open.

**Comment by Alcesmire** [comment]
I know is should be closed, but it's more fun if people get to see this thing. But sure, I'll close it.

**Comment by Zaskoda** [comment]
@The-Feminist-Software-Foundation  - That comment about black american's rights being behind women's rights was a bit inappropriate. The racial pay gap is actually much larger than the gender paygap. Minorities are routinely murdered or jailed for speaking up about their rights. Women's rights are important, but please respect the struggles of others while you fight for them. If you truly feel that minorities have more privlege in the US than women, I beg you to take a deeper look.
